export const LOGIN = {
  START: 'LOGIN_AUTH/START',
  SUCCESS: 'LOGIN_AUTH/SUCCESS',
  FAIL: 'LOGIN_AUTH/FAIL',
}

export const SIGNUP = {
  START: 'SIGNUP/START',
  SUCCESS: 'SIGNUP/SUCCESS',
  FAIL: 'SIGNUP/FAIL',
}

export const REFRESH = {
  START: 'REFRESH/START',
  SUCCESS: 'REFRESH/SUCCESS',
  FAIL: 'REFRESH/FAIL',
}

export const LOGOUT = 'LOGOUT'
