export const GET = {
  START: 'CLIENT/GET/START',
  SUCCESS: 'CLIENT/GET/SUCCESS',
  FAIL: 'CLIENT/GET/FAIL',
}

export const GET_LIST = {
  START: 'CLIENT/GET_LIST/START',
  SUCCESS: 'CLIENT/GET_LIST/SUCCESS',
  FAIL: 'CLIENT/GET_LIST/FAIL',
}

export const GET_CAR_LIST = {
  START: 'CLIENT/GET_CAR_LIST/START',
  SUCCESS: 'CLIENT/GET_CAR_LIST/SUCCESS',
  FAIL: 'CLIENT/GET_CAR_LIST/FAIL',
}

export const PUT_CLINT = {
  START: 'CLIENT/PUT/START',
  SUCCESS: 'CLIENT/PUT/SUCCESS',
  FAIL: 'CLIENT/PUT/FAIL',
}

export const SET = 'CLIENT.SET'
