export const SET = 'CONFIG_TYPE_CATALOG.SET'

export const GET_LIST = {
  START: 'CONFIG_TYPE_CATALOG/GET_LIST/START',
  SUCCESS: 'CONFIG_TYPE_CATALOG/GET_LIST/SUCCESS',
  FAIL: 'CONFIG_TYPE_CATALOG/GET_LIST/FAIL',
}

export const CREATE = {
  START: 'CONFIG_TYPE_CATALOG/CREATE/START',
  SUCCESS: 'CONFIG_TYPE_CATALOG/CREATE/SUCCESS',
  FAIL: 'CONFIG_TYPE_CATALOG/CREATE/FAIL',
}
