export const SET = 'DEALER.SET'

export const GET = {
  START: 'DEALER/GET/START',
  SUCCESS: 'DEALER/GET/SUCCESS',
  FAIL: 'DEALER/GET/FAIL',
}

export const GET_CURRENT = {
  START: 'GET_CURRENT/GET/START',
  SUCCESS: 'GET_CURRENT/GET/SUCCESS',
  FAIL: 'GET_CURRENT/GET/FAIL',
}

export const GET_LIST = {
  START: 'DEALER/GET_LIST/START',
  SUCCESS: 'DEALER/GET_LIST/SUCCESS',
  FAIL: 'DEALER/GET_LIST/FAIL',
}
