export const GET_LIST = {
  START: 'MAILING_HISTORY/GET_LIST/START',
  SUCCESS: 'MAILING_HISTORY/GET_LIST/SUCCESS',
  FAIL: 'MAILING_HISTORY/GET_LIST/FAIL',
}

export const SET = 'MAILING_HISTORY.SET'
