export const SET = 'MAILING_TEMPLATE | SET'

export const CREATE = {
  START: 'MAILING_TEMPLATE | CREATE | START',
  SUCCESS: 'MAILING_TEMPLATE | CREATE | SUCCESS',
  FAIL: 'MAILING_TEMPLATE | CREATE | FAIL',
}

export const GET = {
  START: 'MAILING_TEMPLATE | GET | START',
  SUCCESS: 'MAILING_TEMPLATE | GET | SUCCESS',
  FAIL: 'MAILING_TEMPLATE | GET | FAIL',
}

export const GET_LIST = {
  START: 'MAILING_TEMPLATE | GET_LIST | START',
  SUCCESS: 'MAILING_TEMPLATE | GET_LIST | SUCCESS',
  FAIL: 'MAILING_TEMPLATE | GET_LIST | FAIL',
}

export const REFRESH_LIST = {
  START: 'MAILING_TEMPLATE | REFRESH_LIST | START',
  SUCCESS: 'MAILING_TEMPLATE | REFRESH_LIST | SUCCESS',
  FAIL: 'MAILING_TEMPLATE | REFRESH_LIST | FAIL',
}

export const REMOVE = {
  START: 'MAILING_TEMPLATE | REMOVE | START',
  SUCCESS: 'MAILING_TEMPLATE | REMOVE | SUCCESS',
  FAIL: 'MAILING_TEMPLATE | REMOVE | FAIL',
}

export const UPDATE = {
  START: 'MAILING_TEMPLATE | UPDATE | START',
  SUCCESS: 'MAILING_TEMPLATE | UPDATE | SUCCESS',
  FAIL: 'MAILING_TEMPLATE | UPDATE | FAIL',
}
