export const SET = 'NOTIFICATION | SET'

export const GET_LIST = {
  START: 'NOTIFICATION | GET_LIST | START',
  SUCCESS: 'NOTIFICATION | GET_LIST | SUCCESS',
  FAIL: 'NOTIFICATION | GET_LIST | FAIL',
}

export const GET_NEWEST_LIST = {
  START: 'NOTIFICATION | GET_NEWEST_LIST | START',
  SUCCESS: 'NOTIFICATION | GET_NEWEST_LIST | SUCCESS',
  FAIL: 'NOTIFICATION | GET_NEWEST_LIST | FAIL',
}

export const READ = {
  START: 'NOTIFICATION | READ | START',
  SUCCESS: 'NOTIFICATION | READ | SUCCESS',
  FAIL: 'NOTIFICATION | READ | FAIL',
}

export const REFRESH_LIST = {
  START: 'NOTIFICATION | REFRESH_LIST | START',
  SUCCESS: 'NOTIFICATION | REFRESH_LIST | SUCCESS',
  FAIL: 'NOTIFICATION | REFRESH_LIST | FAIL',
}
