export const SET = 'PARAMS_CONFIG.SET'

export const GET_LIST = {
  START: 'PARAMS_CONFIG | GET_LIST | START',
  SUCCESS: 'PARAMS_CONFIG | GET_LIST | SUCCESS',
  FAIL: 'PARAMS_CONFIG | GET_LIST | FAIL',
}

export const REFRESH_LIST = {
  START: 'PARAMS_CONFIG | REFRESH_LIST | START',
  SUCCESS: 'PARAMS_CONFIG | REFRESH_LIST | SUCCESS',
  FAIL: 'PARAMS_CONFIG | REFRESH_LIST | FAIL',
}

export const REFRESH_FULL_ACTIVE_LIST = {
  START: 'PARAMS_CONFIG | REFRESH_FULL_ACTIVE_LIST | START',
  SUCCESS: 'PARAMS_CONFIG | REFRESH_FULL_ACTIVE_LIST | SUCCESS',
  FAIL: 'PARAMS_CONFIG | REFRESH_FULL_ACTIVE_LIST | FAIL',
}

export const GET = {
  START: 'PARAMS_CONFIG | GET | START',
  SUCCESS: 'PARAMS_CONFIG | GET | SUCCESS',
  FAIL: 'PARAMS_CONFIG | GET | FAIL',
}

export const CREATE = {
  START: 'PARAMS_CONFIG | CREATE | START',
  SUCCESS: 'PARAMS_CONFIG | CREATE | SUCCESS',
  FAIL: 'PARAMS_CONFIG | CREATE | FAIL',
}

export const UPDATE = {
  START: 'PARAMS_CONFIG | UPDATE | START',
  SUCCESS: 'PARAMS_CONFIG | UPDATE | SUCCESS',
  FAIL: 'PARAMS_CONFIG | UPDATE | FAIL',
}
