export const SET = 'TELEMATIC_HISTORY.SET'

export const GET_ONE = {
  START: 'TELEMATIC_HISTORY/GET_ONE/START',
  SUCCESS: 'TELEMATIC_HISTORY/GET_ONE/SUCCESS',
  FAIL: 'TELEMATIC_HISTORY/GET_ONE/FAIL',
}
