export const GET = {
  START: 'TICKET/GET/START',
  SUCCESS: 'TICKET/GET/SUCCESS',
  FAIL: 'TICKET/GET/FAIL',
}

export const SET = 'TICKET.SET'

export const GET_LIST = {
  START: 'TICKET/GET_LIST/START',
  SUCCESS: 'TICKET/GET_LIST/SUCCESS',
  FAIL: 'TICKET/GET_LIST/FAIL',
}
