import { PageableRow } from '@/type/type'

const users = {
  content: [
    {
      collaboratorId: '6543470533889176581',
      username: 'belyaev',
      firstName: 'Роман',
      lastName: 'Беляев',
      middleName: 'Сергеевич',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2018-04-12T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6899250713136486758',
      username: 'Prokopenko',
      firstName: 'Алексей',
      lastName: 'Прокопенко',
      middleName: 'Анатольевич',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2020-11-26T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6743485401271766320',
      username: 'baranov',
      firstName: 'Александр',
      lastName: 'Баранов',
      middleName: 'Вячеславович',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2019-10-03T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6650393237999351130',
      username: 'tur',
      firstName: 'Игорь',
      lastName: 'Тур',
      middleName: 'Олегович',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2019-01-25T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6432122678870086899',
      username: 'amanov',
      firstName: 'Сергей',
      lastName: 'Аманов',
      middleName: 'Борисович',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2013-11-05T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6471172250555199022',
      username: 'morozovsd',
      firstName: 'Станислав',
      lastName: 'Морозов',
      middleName: 'Дмитриевич',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2015-04-06T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6935289748736911682',
      username: 'tretyakovv',
      firstName: 'Виталий',
      lastName: 'Третьяков',
      middleName: 'Александрович',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2021-03-03T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6002834611861087413',
      username: 'miheev1',
      firstName: 'Игорь',
      lastName: 'Михеев',
      middleName: 'Викторович',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2009-07-14T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6603266860128472046',
      username: 'resnyanskiy',
      firstName: 'Максим',
      lastName: 'Реснянский',
      middleName: 'Владимирович',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2018-09-21T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6603551978009951917',
      username: 'mityukov',
      firstName: 'Сергей',
      lastName: 'Митюков',
      middleName: 'Викторович',
      password: null,
      dealerId: 66,
      academyId: '3325543060240461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2018-09-21T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
    {
      collaboratorId: '6603551978009951517',
      username: 'fdgdfg',
      firstName: 'Андрей',
      lastName: 'Пупкин',
      middleName: 'Викторович',
      password: null,
      dealerId: 66,
      academyId: '3325543060222461249',
      permissions: [
        'PERMISSION_DEALER_DATA',
        'PERMISSION_DEALER_CLIENTS',
        'PERMISSION_DEALER_CARS',
        'PERMISSION_MAILINGS',
        'PERMISSION_PARAMS_CONFIG',
      ],
      hireDate: '2018-09-21T00:00:00',
      role: 'ROLE_DEALER_OPERATOR',
      enabled: true,
    },
  ],
  totalElements: 14,
}

export function usersFilter(query: PageableRow): typeof users {
  const offset = query.page * query.size

  const content = users.content.slice(offset, offset + query.size)

  return {
    content,
    totalElements: users.content.length,
  }
}

export default users
